name: better_player_example
description: Better Player example usage app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  better_player:
    # path: plugins/betterplayer
    path: ../
    # git:
    #   url: git@github.com:yy1300326388/betterplayer.git
    #   ref: 0.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.10
  visibility_detector: ^0.3.3
  collection: ^1.16.0
  video_player_platform_interface: ">=6.1.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
